-- 1학년 14반
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(101, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(102, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(103, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(104, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(106, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(107, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(108, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(109, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(110, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(111, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(112, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(113, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(114, 0);

-- 2학년 14반
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(201, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(202, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(203, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(204, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(205, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(206, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(207, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(208, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(209, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(210, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(211, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(212, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(213, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(214, 0);
-- 3학년 14반
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(301, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(302, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(303, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(304, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(305, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(306, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(307, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(308, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(309, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(310, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(311, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(312, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(313, 0);
INSERT INTO SURVEY_EVENT (STUNO, CLASSCOUNT) VALUES(314, 0);